# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ZaiGuiTmData.ptoto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ZaiGuiTmData.ptoto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12ZaiGuiTmData.ptoto\x12\x05space\"S\n\tValEntity\x12\r\n\x05param\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\r\x12\x0b\n\x03raw\x18\x03 \x01(\x0c\x12\x0b\n\x03val\x18\x04 \x01(\x06\x12\x0f\n\x07\x64isplay\x18\x05 \x01(\t\"\x84\x01\n\x0fTmvldataMessage\x12\x0e\n\x06msglen\x18\x01 \x01(\r\x12\x0c\n\x04type\x18\x02 \x01(\r\x12\x0b\n\x03sat\x18\x03 \x01(\t\x12\x0c\n\x04\x66low\x18\x04 \x01(\t\x12\x0b\n\x03\x63nt\x18\x05 \x01(\r\x12\x0c\n\x04time\x18\x06 \x01(\x01\x12\x1d\n\x03val\x18\x07 \x03(\x0b\x32\x10.space.ValEntityb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ZaiGuiTmData.ptoto_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VALENTITY']._serialized_start=29
  _globals['_VALENTITY']._serialized_end=112
  _globals['_TMVLDATAMESSAGE']._serialized_start=115
  _globals['_TMVLDATAMESSAGE']._serialized_end=247
# @@protoc_insertion_point(module_scope)
